services:
  api:
    build: .
    container_name: ktor-api
    ports:
      - "8080:8080"
    environment:
      - postgres_db_url_port=jdbc:postgresql://db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: db
    ports:
      - "8081:5432"
    volumes:
      - ./db/tmp:/var/lib/postgresql/data
    env_file:
      - db/postgres.env
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 1s
      start_period: 5s
      retries: 3
      timeout: 10s